# Generated by Django 2.2.1 on 2019-10-08 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('login', models.IntegerField(unique=True)),
                ('avatar_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='url field', max_length=15)),
                ('url', models.URLField(help_text='url field')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RestAPI.Actor')),
                ('repo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RestAPI.Repo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
