# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-11 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('avatar_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RestAPI.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='name field', max_length=50)),
                ('url', models.URLField(help_text='url field')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repos', to='RestAPI.Repo'),
        ),
    ]
