# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-10 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='repo',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='event',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RestAPI.Actor'),
        ),
    ]
